//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntMe.Plugin.Mdx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Models {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Models() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AntMe.Plugin.Mdx.Models", typeof(Models).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ant {
            get {
                object obj = ResourceManager.GetObject("ant", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] anthill {
            get {
                object obj = ResourceManager.GetObject("anthill", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] apple {
            get {
                object obj = ResourceManager.GetObject("apple", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] bug {
            get {
                object obj = ResourceManager.GetObject("bug", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sugar {
            get {
                object obj = ResourceManager.GetObject("sugar", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abby
        ///Abelina
        ///Abigail
        ///Adelaide
        ///Adeline
        ///Adina
        ///Adriana
        ///Adrienne
        ///Afra
        ///Agatha
        ///Agnes
        ///Aida
        ///Aimee
        ///Aischa
        ///Ajlin
        ///Albertine
        ///Alea
        ///Aleksandra
        ///Alena
        ///Alessa
        ///Alessandra
        ///Alessia
        ///Alexa
        ///Alexandra
        ///Alexia
        ///Alexis
        ///Alice
        ///Alicia
        ///Alida
        ///Alina
        ///Aline
        ///Alisa
        ///Alissa
        ///Alisson
        ///Amabella
        ///Amadea
        ///Amanda
        ///Amelia
        ///Amelie
        ///Amina
        ///Amy
        ///Ana
        ///Anastasia
        ///Andrea
        ///Andrina
        ///Anette
        ///Angela
        ///Angelika
        ///Angelina
        ///Angelique
        ///Anina
        ///Anine
        ///Anita
        ///Anja
        ///Anjalie
        ///Anke
        ///Ann
        ///Anna
        ///Annabel
        ///Annabell
        ///Annabella
        ///Annabelle
        ///Anne
        ///A [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string vornamen {
            get {
                return ResourceManager.GetString("vornamen", resourceCulture);
            }
        }
    }
}
